### ISSUE TITLE
✨ Programatic way of triggering the html export 

### ISSUE THREAD

**Issue by juan11iguel** [ebullient/obsidian-slides-extended#11]
### 🔖 Feature description

Right now we are able to export the presentation as an `html`. This is very useful to create static webpages or in general, to have very customizable and interactive presentations that can be viewed just using a web browser.

However, as far as I know, the only option to trigger this export is through the GUI in the Slide preview window:
![image](https://github.com/ebullient/obsidian-slides-extended/assets/48693399/f10bb1d5-273d-4a02-9e1f-b4d461351a57)

Thanks!

### ✔️ Solution

I wonder if there could be a programatic way of triggering this export / build process. This would be useful to automatically create updated presentations from some source code, as mentioned in [this](https://forum.obsidian.md/t/anyway-to-run-the-advanced-slides-export-as-html-in-a-github-action/70883/2) obsidian community question.

### 📝 Additional Context

If I am not mistaken under the hood advanced/extended slides is using the hugo engine, but apart from that I am not quite sure about the way of building the static website by using hugo from the source presentation files, I am sure there are a lot of customizations applied to generate the pages and that it would be better to have some exposed API on the plugin to trigger this process.

**Comment by ebullient** [comment]
Slides extended itself is not using the hugo engine. It's using fastify. 

Hugo was used for creating the docs site for Advanced Slides. The docs for extended slides haven't been finished, as I won't be using hugo (I have some decisions to make on how to do this, so I just haven't. ;) )

**Comment by ebullient** [comment]
Can you explain how you would want this to work? 

Are you thinking of an Obsidian command or something else?

**Comment by juan11iguel** [comment]
You are right, a command would be a good addition, but still it would be required to manually open obsidian and trigger the build (unless there is a way of doing it without actually opening the GUI?).

I think for this kind of use case, using a tool like [marp](https://github.com/marp-team/marp) probably makes more sense

**Comment by ebullient** [comment]
> You are right, a command would be a good addition, but still it would be required to manually open obsidian and trigger the build (unless there is a way of doing it without actually opening the GUI?).

This particular plugin is meant to work with Obsidian, which does mean Obsidian needs to be running. It isn't intended to be an SSG, and I'm not sure I want to spend the time trying to create something standalone that is well outside the purpose of the plugin. 

> I think for this kind of use case, using a tool like [marp](https://github.com/marp-team/marp) probably makes more sense.

If you're looking for something headless, I think that's right. The trick here, if you're editing material within Obsidian, is watching the links you're using: relative markdown links could work, but wikilinks may not, depending on how any other tool chooses to resolve links. This plugin has some tricks to resolve resources across vault and plugin directories, which is another wrench to throw at you if you want to have something that runs standalone.
