### ISSUE TITLE
✨ Mobile Support 

### ISSUE THREAD

**Issue by globalhuman** [ebullient/obsidian-slides-extended#17]
### 🔖 Feature description

Being able to utilise this plugin on mobile would be a great addition to this plugin to allow presentations on android, ios, phones and tablets. 

### ✔️ Solution

Slides extended on mobile OS

### ❓ Alternatives

Obsidian has a Core Plugin called Slides which is very primitive and basic

**Comment by ebullient** [comment]
This is unlikely. Slides Extended uses fastify, which relies on node, which is not present in the mobile version of Obsidian.

**Comment by ebullient** [comment]
closing for now. I would love mobile support myself, but I'm not going to swim upstream for node support any time soon.
