### ISSUE TITLE
Use another port than 3000

### ISSUE THREAD

**Issue by SuzanaK** [ebullient/obsidian-slides-extended#18]
### 🔖 Feature description

3000 is a typical frontend development port and it shows in the netstat output only as "app.asar" so it took me a while to find out that it's this plugin that is blocking my local nodejs app to start. 

Could you please set another port that's less in use? :pray: 

### ✔️ Solution

If you tell me what port to use instead I can make a PR.

**Comment by ebullient** [comment]
There is already a configuration option for this:

<img width="442" alt="image" src="https://github.com/user-attachments/assets/b427ef8f-654a-494f-a9ad-8ee663ec6386">
