### ISSUE TITLE
✨ Please set up recurring sponsorship

### ISSUE THREAD

**Issue by 0atman** [ebullient/obsidian-slides-extended#21]
### 🔖 Feature description

I would like to support the project on an ongoing basis, and I recommend setting up a Patreon for the project (and github sponsors if you so wish)

My full-time income (I'm a [YouTuber](https://www.youtube.com/@NoBoilerplate)) is based on advanced slides, and while I am saddened that @MSzturc is not developing advanced slides publicly any more (Matt, thank you for your incredible work), I am relieved there is a fork to rally behind.

### ✔️ Solution

Set up both patreon and gh sponsors, my professional recommendation of the monthly price of the tiers is:

1. $2
2. $5
3. $10
4. $50

(the seemingly-unrealistic high tier is not too high for some people, and you want to let them support you)

### ❓ Alternatives

<https://ko-fi> is fine too, but lacks the brand awareness of patreon and gh sponsors, but if you're feeling energetic, you may set that up too.

### 📝 Additional Context

Thank you again for re-energising this project!

**Comment by ebullient** [comment]
I use Buy Me a Coffee: https://buymeacoffee.com/ebullient

Patreon is more work for me than I'm interested in dealing with.

I did set up your recommended membership tiers. I did not expect anyone to be interested. 🥰

**Comment by 0atman** [comment]
Super! Thank you so much again, I've subscribed on BMAC - perfect! :heart:
