### ISSUE TITLE
✨ Support videos using obsidian syntax + Copying files at export file

### ISSUE THREAD

**Issue by marcbenedi** [ebullient/obsidian-slides-extended#22]
### 🔖 Feature description

Hi,

When can we expect PR from the original repository to be merged with this one?

A while ago, I submitted PR #261 (see below) to insert videos using obsidian syntax and copying the files when exporting the slides.

---

Hi,

I had been experiencing this issue for a while aswell https://github.com/MSzturc/obsidian-advanced-slides/issues/260 .

This PR adds support to videos included with obsidian syntax (which were not rendered before)

```md
![[myVideo.mp4]]
```

And copies the video file when exporting the slides. It also copies the file if it is embedded using html code. For example:

```html
<video data-autoplay="" controls="" loop="" height="700" data-paused-by-reveal="">
  <source src="/99-Attachments/2023-09-12_jumping_jacks.mp4" type="video/mp4">
</video>
```

### ✔️ Solution

I implemented it in the original repository a while ago:

https://github.com/MSzturc/obsidian-advanced-slides/pull/261

**Comment by ebullient** [comment]
If you have a PR that you would like to have integrated, you'll need to bring it to this fork and make sure it still works w/ fastify + newer reveal.js.

I'm happy to work with your contribution, but I haven't been scrubbing the other repo for pending work.

**Comment by ebullient** [comment]
I've taken a stab at a different approach to this in the latest release (extended image collector to also handle videos, as processing is more or less the same).
