### ISSUE TITLE
Issue - local images are not displayed

### ISSUE THREAD

**Issue by ebullient** [ebullient/obsidian-slides-extended#24]
### Discussed in https://github.com/ebullient/obsidian-slides-extended/discussions/14

<div type='discussions-op-text'>

<sup>Originally posted by **AM-FX** June  2, 2024</sup>
Before creating a issue I wanted to ask, if its maybe a user error instead a bug.
Loving the plugin so far and would like to do all my presentations with it from now on if possible 🙂   

I am new to the plugin and tried out advanced slides shortly before. 

The issue is that local image embeds dont work at all for me. Not in the preview and also not in the browser and returns the following: 
```
Failed to load resource: the server responded with a status of 404 (Not Found)
```

different formattings i tried that worked with advanced slides: 
```
%% Default %%
![[Out_3.jpg|300x250]]
 
%% Relative Path %%
![](../_ImagesCollection/Out_3.jpg) 
```
![Screenshot 2024-06-02 124259](https://github.com/ebullient/obsidian-slides-extended/assets/80644364/2cd7e040-1d06-41dc-8973-91c0ef0a16f4)

weblinks do work: 
```
![](https://picsum.photos/id/1005/250/250)
```

tried multiple things already:
- reinstalling
- stopping and reenabling the extended slides server
- back and forth testing with advanced slides

best regards,
AM</div>

**Comment by teecrow** [comment]
This issue still persists for me. In the same synced vault across two machines -- one Mac and one Windows 10 -- local images embed without issue on the Mac but not on the Windows machine. In Dev Tools > Source, the image (Which is in my obsidian vault root) is nowhere to be found under the contents of localhost:3000. Obsidian v1.6.7 and Slides Extended v2.1.2. FWIW, here is the slide that doesn't work:
```
---

another go at images:
![](attnpaper-pic.png)

---
```

![image](https://github.com/user-attachments/assets/cdcd2bfb-67b1-41ee-8cfa-1d4f4120874e)
![image](https://github.com/user-attachments/assets/2c3ba5f9-6c26-43ae-98bc-7994a731a4ed)

**Comment by ebullient** [comment]
I added some additional diagnostics in the latest release. Please open a new issue if this still occurs, and include messages related to finding/resolving files that occur in the developer console.

**Comment by AM-FX** [comment]
Hello ebullient,

I have just tested it with version 2.1.3 and unfortunately it still behaves exactly the same. The local images are apparently not included by the server. In the console I only have the same message as before:

```
Failed to load resource: the server responded with a status of 404 (Not Found) img_b.jpg:1
```
![image](https://github.com/user-attachments/assets/7eb0a79f-80e6-473e-8473-011207a79e0c)

Best regards,
AM-FX

**Comment by ebullient** [comment]
as I said, please open a new issue.

You have "default levels" for logging, please include "verbose" logs.
