### ISSUE TITLE
🐛 Slide Preview showing incorrectly

### ISSUE THREAD

**Issue by devinat1** [ebullient/obsidian-slides-extended#6]
**Describe the bug**
I create a new file and slide preview it, and get  rather than actual slides.

**To Reproduce**
Create a file and try to preview it

**Expected behavior**
Able to see different slides

**Screenshots**
![image](https://github.com/ebullient/obsidian-slides-extended/assets/15788108/db3953ec-4c77-4b6d-94d5-d76d41eb2eb6)

**Additional context**
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.4.16
	Operating system: Windows 10 Home 10.0.26100
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.5.4
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 65
	Plugins enabled: 33
		1: Templater v2.2.3
		2: Tab Switcher v1.4.0
		3: Google Photos v1.6.5
		4: Dataview v0.5.66
		5: Editor Syntax Highlight v0.1.3
		6: Minimal Theme Settings v7.5.0
		7: Commander v0.5.1
		8: Canvas Mindmap v0.1.9
		9: Auto Link Title v1.5.3
		10: Admonition v10.2.0
		11: Simple CanvaSearch v0.1.0
		12: QuickAdd v1.8.1
		13: Excalidraw v2.1.3
		14: Todoist Sync v1.12.0
		15: Linter v1.23.2
		16: Readwise Official v2.0.1
		17: Enhancing Export v1.10.4
		18: Zotero Integration v3.1.7
		19: Paste URL into selection v1.7.0
		20: Note Refactor v1.8.2
		21: Canvas Filter v0.9.4
		22: Ghost Fade Focus v3.0.0
		23: WakaTime v1.0.0
		24: Quick Switcher++ v4.1.0
		25: Recent Files v1.3.10
		26: ExcaliBrain v0.2.15
		27: Projects v1.17.2
		28: Periodic Notes v0.0.17
		29: Homepage v3.8.0
		30: Calendar v1.5.10
		31: Longform v2.0.7
		32: BRAT v1.0.1
		33: Slides Extended v2.0.6

**Comment by devinat1** [comment]
Additionally, I am getting this:
![image](https://github.com/ebullient/obsidian-slides-extended/assets/15788108/8ddc3225-e6ab-4727-ba8c-2d0cf9d8ba4a)

**Comment by devinat1** [comment]
That appears to be only for text of a certain length. If I change "Structure of Overview" to just "Structure", then it fixes. Still annoying though.

**Comment by devinat1** [comment]
Yet another issue is that bullet points don't show in the right size
![image](https://github.com/ebullient/obsidian-slides-extended/assets/15788108/4019da6a-d93d-4efc-9ab5-8063d9393e07)
This is not always the case:
![image](https://github.com/ebullient/obsidian-slides-extended/assets/15788108/b37c32fa-f001-496d-a8b9-4786ed79849d)

**Comment by devinat1** [comment]
Another issue with text
![image](https://github.com/ebullient/obsidian-slides-extended/assets/15788108/8f28954d-d1ae-488d-a2ae-4230a7618365)

**Comment by ebullient** [comment]
Preview mode for slides definitely works.

Looking at and working in source mode will be more useful for you (and for me) than looking at live preview. Styles are set/changed using html comments, and from your screenshots, I can't tell if any of them are actually correct.

I'll be putting together more examples shortly, but I recommend starting with other examples first, and then writing your own.

We have some there: 
https://github.com/ebullient/obsidian-slides-extended/discussions/2

I also still have to fix up the docs, but the examples from Advanced Slides still apply: 
https://mszturc.github.io/obsidian-advanced-slides/getting-start/firststeps/
