### ISSUE TITLE
🐛 Failed to load plugin "slides-extended" v2.1.4 on MacOS

### ISSUE THREAD

**Issue by ellerychan** [ebullient/obsidian-slides-extended#79]
### Input data (markdown source)

N/A

### Expected Behavior

Expected plugin to update and load successfully.

### Current behaviour

When plugin Enable is attempted, pops up error message 'Failed to load plugin "slides-extended"', does not enable.

### Steps to reproduce

1. Launch Obsidian Sandbox
2. Go to Settings -> Community Plugins
3. Browse, find Slides Extended
4. Click Install
5. Click Enable
6. Plugin does not enable, but instead produces 'Failed to load plugin "slides-extended"' message

Environment: M3 Macbook Pro, macOS Sequoia 15.1.1, Obsidian 1.7.7, Slides Extended 2.1.4

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version

1.7.7

### Slides Extended Plugin Version

2.1.4

### Checks

- [X] I have tried it in the sandbox vault with only this plugin enabled

**Comment by ebullient** [comment]
will have a look, thanks

**Comment by ebullient** [comment]
I just tried this on the sandbox vault with no issues (on a mac).

Can you try it in the sandbox vault?

Alternately:

1. Uninstall the plugin
2. Restart Obsidian
3. Open the developer console
4. re-install the plugin.

If it fails, please include any messages related to slides extended from the console.

**Comment by ellerychan** [comment]
Failed in my sandbox vault also.  It succeeds on the `Install`, but fails on `Enable`.

![image](https://github.com/user-attachments/assets/348753d1-cd0f-4a74-ac5e-98976b5739dc)

Here is the saved Developer Console log:
```
app.js:1 Obsidian Developer Console
app.js:1 Plugin failure: slides-extended TypeError: dte.tracingChannel is not a function
    at eval (plugin:slides-extended:8:37744)
    at eval (plugin:slides-extended:6:330)
    at eval (plugin:slides-extended:8:38470)
    at eval (plugin:slides-extended:6:330)
    at eval (plugin:slides-extended:109:14388)
    at eval (plugin:slides-extended:6:330)
    at eval (plugin:slides-extended:367:26992)
    at eval (plugin:slides-extended:6:330)
    at anonymous (plugin:slides-extended:475:21425)
    at e.<anonymous> (app.js:1:2199465)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
e.enablePlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
e.enablePluginAndSave @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
(anonymous) @ app.js:1
```

Thank you for your work on this plugin.  I'm teaching coding to a couple of grade-schoolers and it's been very helpful.

**Comment by blkdark** [comment]
The same for me.


Input data (markdown source)

N/A
Expected Behavior

Expected plugin to update and load successfully.
Current behaviour

When plugin Enable is attempted, pops up error message 'Failed to load plugin "slides-extended"', does not enable.
Steps to reproduce

    Launch Obsidian Sandbox
    Go to Settings -> Community Plugins
    Browse, find Slides Extended
    Click Install
    Click Enable
    Plugin does not enable, but instead produces 'Failed to load plugin "slides-extended"' message

Environment: ASUS, Windows 11, Obsidian 1.7.7, Slides Extended 2.1.4
Which Operating Systems are you using?

    Android
    iPhone/iPad
    Linux
    macOS
    Windows

Obsidian Version

1.7.7
Slides Extended Plugin Version

2.1.4
Checks

   

Possible solution

No response

this is the  copy of devtools:

Plugin failure: slides-extended TypeError: dte.tracingChannel is not a function
    at eval (plugin:slides-extended:8:37744)
    at eval (plugin:slides-extended:6:330)
    at eval (plugin:slides-extended:8:38470)
    at eval (plugin:slides-extended:6:330)
    at eval (plugin:slides-extended:109:14388)
    at eval (plugin:slides-extended:6:330)
    at eval (plugin:slides-extended:367:26992)
    at eval (plugin:slides-extended:6:330)
    at anonymous (plugin:slides-extended:475:21425)
    at e.<anonymous> (app.js:1:2199465)
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at a (app.js:1:236051)

**Comment by cbchoi** [comment]
I have the same issue here.
I'm on Windows, and there's something wrong with version 2.1.4.
I have reinstalled the v2.1.3, and there is no problem

**Comment by ebullient** [comment]
ok. I've reverted fastify. I think the reference to the tracingChannel was added in the more recent version. It is weird that I don't see the issue locally with the sandbox vault... makes it difficult to test/understand.

**Comment by ebullient** [comment]
Release is in flight. If you could both pick up 2.1.5 when it is available and LMK if it is ok, that would be lovely.

**Comment by ellerychan** [comment]
The 2.1.5 update works for me!

> which installer are you using?

I am just installing from the Community Plugins Browse panel in Obsidian, and clicking on the `Install` button.

**Comment by ellerychan** [comment]
Ah, sorry.  Obsidian Installer 1.5.8.

**Comment by ebullient** [comment]
AH HA. The latest installer is 1.7.5. You're considerably behind.

**Comment by ellerychan** [comment]
> The latest installer is 1.7.5.

I updated it just now and got Installer 1.7.7.

I'm fairly new to Obsidian and did not realize the installer was a separate entity that needs to be updated.  Thanks.
