### ISSUE TITLE
✨ Replacing reveal.html

### ISSUE THREAD

**Issue by matthewturk** [ebullient/obsidian-slides-extended#8]
**Is your feature request related to a problem? Please describe.**

I'd like to have a bit finer grained control over the way `reveal.html` is constructed.

**Describe the solution you'd like**

We can specify the `.css` files that replace the themes, but being able to replace the template would be really useful in some contexts as well.  For instance, this might allow adding plugins that are not of general interest, or having template slides that are always included, etc.

**Describe alternatives you've considered**

I *believe* that there are some operations that need modification of the HTML to work, but I'm also currently investigating how much of this can be done via injection in HTML blocks or just directly in the CSS themes.  So far I'm not able to do everything quite yet.

Thank you for considering this!

**Comment by ebullient** [comment]
This is me handing you a dangerous thing. ;)

In settings, you can configure a "Theme directory", which is a folder in your vault that will be added to the search path when looking for slide and highlight themes.

If you create an `html` directory in that, you can copy reveal.html and/or embed.html, and customize them. They are mustache templates, and you can definitely break the planet, and if I fix something you'll have to resolve the difference..

**Comment by matthewturk** [comment]
Oh, outstanding!  Thank you so much @ebullient !  I appreciate you trusting me/us with this dangerous thing and I'll do my best to live up to that. :)
